version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - global-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    networks:
      - global-network

  strapi:
    container_name: strapi
    restart: unless-stopped
    build:
      context: ./cms
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "1337:1337"
    env_file: ./cms/.env
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=mydb
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=root
      - DATABASE_SSL=false
    volumes:
      - ./cms/public/uploads:/opt/app/public/uploads
    networks:
      - global-network

  nginx:
    container_name: nginx
    depends_on:
      - api
      - client
    restart: always
    build: ./nginx
    ports:
      - "3050:80"
    networks:
      - global-network

  api:
    container_name: api
    build: ./backend
    environment:
      - PGUSER=admin
      - PGHOST=postgres
      - PGDATABASE=mydb
      - PGPASSWORD=root
      - PGPORT=5432
    networks:
      - global-network

  client:
    container_name: client
    stdin_open: true
    build: ./frontend
    networks:
      - global-network


volumes:
  pgdata:
  pgadmin:

networks:
  global-network:
    name: Global
    driver: bridge