FROM node:16-alpine
# Installing libvips-dev for sharp Compatibility
RUN apk update && apk add  build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /opt/app
COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run build
EXPOSE 1337
CMD ["npm", "run", "develop"]
